apiVersion: apps/v1
kind: Deployment
metadata: 
  name: jhooq-springboot
spec:
  replicas: 3
  selector: 
    matchlabels: 
      app: jhooq-springboot
  template:
    metadata:
      labels: 
        app: jhooq-springboot
    spec: 
      containers:
        - name: springboot
          image: 9841/testimage:1.0
          ports:
            - containerport: 8080
          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: jhooq-springboot
spec:              
  type: LoadBalancer
  ports:
    - port: 80
      targetport: 8080
  selector: 
    app: jhooq-springboot